# Generated by Django 4.2.9 on 2024-02-22 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="subjects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cont", models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="contactform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("message", models.TextField(max_length=2000)),
                (
                    "problems",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.subjects"
                    ),
                ),
            ],
        ),
    ]
