# Generated by Django 4.2.9 on 2024-02-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_subjects_contactform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subjects",
            name="cont",
            field=models.CharField(default=None, max_length=200),
        ),
    ]
