# Generated by Django 4.2.9 on 2024-02-25 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_customerprofile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart", old_name="quality", new_name="quantity",
        ),
    ]
