# Generated by Django 4.2.9 on 2024-02-26 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("myapp", "0005_rename_quality_cart_quantity"),
    ]

    operations = [
        migrations.CreateModel(
            name="orders_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quntity", models.PositiveIntegerField()),
                ("Address", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("APPROVED", "APPROVED"), ("DELIVERD", "DELIVERD")],
                        default="pending",
                        max_length=100,
                    ),
                ),
                ("total_amount", models.IntegerField()),
                ("fname", models.CharField(default=0, max_length=100)),
                ("mobile_no", models.CharField(default=0, max_length=100)),
                ("email", models.EmailField(default=0, max_length=100)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.product_model",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
